name: S11 - DAST (ZAP)
on:
  workflow_dispatch:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/ci-s11-dast.yml'

jobs:
  s11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure evidence dirs
        run: mkdir -p EVIDENCE/S11

      - name: Setup Python & run app
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: uvicorn app.main:app --host 0.0.0.0 --port 8080 &
      - run: timeout 20 bash -c 'until curl -sf http://localhost:8080/healthz; do sleep 1; done'

      - name: Ensure evidence dirs
        run: |
          mkdir -p EVIDENCE/S11
          chmod 777 EVIDENCE/S11
      
      - name: ZAP Baseline (root, write to /zap/wrk)
        run: |
          set -euxo pipefail
          docker run --rm --network host \
            -u 0:0 \
            -v "${{ github.workspace }}/EVIDENCE/S11:/zap/wrk" \
            zaproxy/zap-stable \
            /zap/zap-baseline.py \
              -t http://localhost:8080 \
              -r zap_baseline.html \
              -J zap_baseline.json \
              -d
          ls -la EVIDENCE/S11
      
      - name: Upload S11 evidence
        uses: actions/upload-artifact@v4
        with:
          name: S11_EVIDENCE
          path: EVIDENCE/S11
